name: Build and deploy container app to Azure Web App - ai-archivai

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      safe_tag: ${{ steps.extract_tag.outputs.SAFE_TAG }}

    steps:
      # 1. Grab the latest commit message and sanitize it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Commit Message and Create Docker Tag
        id: extract_tag
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%s)
          # Lowercase + non-alphanumerics → dash
          SAFE_TAG=$(echo "$COMMIT_MESSAGE" \
            | tr '[:upper:]' '[:lower:]' \
            | tr -cs 'a-z0-9' '-' )
          # Truncate to first 50 chars
          SAFE_TAG=${SAFE_TAG:0:50}
          echo "SAFE_TAG=$SAFE_TAG" >> $GITHUB_OUTPUT

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to your ACR
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: archivaidb.azurecr.io
          username: ${{ secrets.AzureAppService_ContainerUsername_52c1dbfa59d74f9ebdfa00b7a4d10453 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_8fe7b7a53d0948acab70b895f34a3f40 }}

      # 4. Build & push with SAFE_TAG and latest
      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            archivaidb.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_52c1dbfa59d74f9ebdfa00b7a4d10453 }}:${{ steps.extract_tag.outputs.SAFE_TAG }}
            archivaidb.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_52c1dbfa59d74f9ebdfa00b7a4d10453 }}:latest
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ai-archivai'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_2e8febb7479641d4b8a78d7a14b2fce4 }}
          images: >
            archivaidb.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_52c1dbfa59d74f9ebdfa00b7a4d10453 }}:${{ needs.build.outputs.safe_tag }}
