# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - archivai-ai

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://archivaidb.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_54eed22efcd04ca2b86d8f83fa519aa7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f0895522774d4c51b5c196c7c3fc25d7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: archivaidb.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_54eed22efcd04ca2b86d8f83fa519aa7 }}/github-archivai:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'archivai-ai'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_54501f0f86cc4115a352f1d3941673ad }}
        images: 'archivaidb.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_54eed22efcd04ca2b86d8f83fa519aa7 }}/github-archivai:${{ github.sha }}'